apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginxhello-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    #git: ssh://git@github.com/devon-it/gitops-test.git
    git: https://github.com/devon-it/gitops-test.git
    path: helm/chart
    ref: main
  rollback:
    enable: true
    retry: true
