apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginxhello-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
spec:
  chart:
    git: git@github.com:${GHUSER}/gitops-test-helm
    path: helm/chart
    ref: main
  rollback:
    enable: true
    retry: true
